name: Export
on: [push]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Install OpenSCAD"
        run: |
          sudo apt update
          sudo apt install openscad
      - name: "Export stl files for 3D printing"
        run: |
          mkdir stls
          openscad oring.scad -o stls/oring.stl
          openscad mold.scad -o stls/mold.stl
          openscad socket.scad -o stls/socket.stl
          openscad bung.scad -o stls/bung.stl
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stls
          path: stls/
