name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Build artifacts"
        run: |
          sudo apt update
          sudo apt install openscad
          mkdir stls
          openscad oring.scad -o stls/oring.stl
          openscad mold.scad -o stls/mold.stl
          openscad socket.scad -o stls/socket.stl
          openscad bung.scad -o stls/bung.stl
          zip -rj stls.zip stls

      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is an initial release. The designs have not yet been validated yet.
          draft:  true
          prerelease: true

      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stls.zip
          asset_name: stls.zip
          asset_content_type: application/zip
